### ISSUE TITLE
Doesn't Seem to Work with HA 2021.7.4. Or is it my channel?

### ISSUE THREAD

**Issue by jtitley** [custom-components/youtube#42]
**Version of the custom_component**

Latest version

**Describe the bug**
I see there are previous reports of this not working without any sign in the error log. This is exactly the issue that I'm facing. It's weird, if there are errors, they aren't being logged. Any ideas?

My config:
  - platform: youtube
    channel_id: UCaCE5pzy49M8nQ59plgmFOA

**log**

```
2021-08-05 10:19:35 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration youtube which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-05 10:20:05 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform youtube is taking over 10 seconds.
```

**Comment by jtitley** [comment]
Issue is with the title. It is blank, so the sensor isn't created. The logging also is all debug. It would be helpful if error and warnings are used for proper debugging. I don't know why title isn't working, but I created a new property where you can put a default name in the config. I will create a pull request with these changes, and I think it will be helpful as this change helped me to get this to work. 

Maybe someone can figure out why title isn't working? If I parse manually, it's extracted properly. But not in the code.

**Comment by pinkywafer** [comment]
I have created a sensor using your config above, and it is working perfectly here - channel shows as `Relax Cafe Music` 
This was on the latest Home Assistant (2021.8.1)
can you give any  further information about your install.

I don't like the idea of creating the sensor if it the channel title cannot be parsed - to me, this seems more like "sticking a band-aid" rather than solving the problem,
BUT I definitely agree that error / warnings would be helpful in the logs.
