### ISSUE TITLE
Use state of my subscription feed instead of specific channel

### ISSUE THREAD

**Issue by rileytb** [custom-components/youtube#61]
**Is your feature request related to a problem? Please describe.**
I'd like all my Youtube subscription notifications to come through HA, but adding each and every subscription (and it's subsequent automation) is a lot and can be a lot to maintain. 

**Describe the solution you'd like**
So, rather than adding each of my subscriptions as a sensor, I was wondering if this project could somehow point to my subscription feed and use that instead.

**Describe alternatives you've considered**
Alternatives... I guess would be adding each channel I sub to as a sensor and create automation for it.

**Comment by pinkywafer** [comment]
This could be a possibility, but rather than being a simple sensor would require an authorized request to the API.

What would be the best way of implementing the result? - 1 sensor for the most recent subscribed channel which updates when uploads are made by any subscribed channel? or maybe a sensor which shows the last 5? or a choice of a number of sensors of most recent? or an individual sensor for each subscribed channel?

The last option would end up being fairly heavy on resources and rack up a lot of api hits depending on how many channels are subscribed to.

**Comment by rileytb** [comment]
This seems like a pretty big change for the project: `would require an authorized request to the API` because right now it's all anonymous, right?
Maybe a different sensor/project would be the answer?

Also, looking into the sensor code it looks like it uses the Youtube feed (XML or RSS or whatever it's called) to grab the latest values. After looking around a bit I couldn't find that same style of feed for a subscription feed, so again, maybe another project would be best. 

If it does wind up being possible and something for this project... 
For me I think this way would be just fine: `1 sensor for the most recent subscribed channel which updates when uploads are made by any subscribed channel`. 
Unless there's a possibility in between scrapes that multiple channels have uploaded and you'll have missed the second latest...

**Comment by pinkywafer** [comment]
Ok. I'm not going to include this here as using authorized API requests is indeed a big change, which would also require more configuration, so I'm going to leave this.
